const employees = [
  {
    ID: 1,
    FirstName: "John",
    LastName: "Heart",
    Gender: "Male",
    "Date of Birth": "1964/03/16",
    Address: "351 S Hill St.",
  },
  {
    ID: 2,
    FirstName: "Olivia",
    LastName: "Peyton",
    Gender: "Male",
    "Date of Birth": "1981/06/03",
    Address: "807 W Paseo Del Mar",
  },
  {
    ID: 3,
    FirstName: "Robert",
    LastName: "Reagan",
    Gender: "Male",
    "Date of Birth": "1974/09/07",
    Address: "4 Westmoreland Pl.",
  },
  {
    ID: 4,
    FirstName: "Greta",
    LastName: "Sims",
    Gender: "Male",
    "Date of Birth": "1977/11/22",
    Address: "1700 S Grandview Dr.",
  },
  {
    ID: 5,
    FirstName: "Brett",
    LastName: "Wade",
    Gender: "Male",
    "Date of Birth": "1968/12/01",
    Address: "1120 Old Mill Rd.",
  },
  {
    ID: 6,
    FirstName: "Sandra",
    LastName: "Johnson",
    Gender: "Male",
    "Date of Birth": "1974/11/15",
    Address: "4600 N Virginia Rd.",
  },
  {
    ID: 7,
    FirstName: "Kevin",
    LastName: "Carter",
    Gender: "Male",
    "Date of Birth": "1978/01/09",
    Address: "424 N Main St.",
  },
  {
    ID: 8,
    FirstName: "Cynthia",
    LastName: "Stanwick",
    Gender: "Male",
    "Date of Birth": "1985/06/05",
    Address: "2211 Bonita Dr.",
  },
  {
    ID: 9,
    FirstName: "Kent",
    LastName: "Samuelson",
    Gender: "Male",
    "Date of Birth": "1972/09/11",
    Address: "12100 Mora Dr",
  },
  {
    ID: 10,
    FirstName: "Taylor",
    LastName: "Riley",
    Gender: "Male",
    "Date of Birth": "1982/08/14",
    Address: "7776 Torreyson Dr",
  },
  {
    ID: 11,
    FirstName: "Sam",
    LastName: "Hill",
    Gender: "Male",
    "Date of Birth": "1984/02/17",
    Address: "645 Prospect Crescent",
  },
  {
    ID: 12,
    FirstName: "Kelly",
    LastName: "Rodriguez",
    Gender: "Male",
    "Date of Birth": "1988/05/11",
    Address: "1601 W Mountain St.",
  },
  {
    ID: 13,
    FirstName: "Natalie",
    LastName: "Maguirre",
    Gender: "Male",
    "Date of Birth": "1977/10/07",
    Address: "6400 E Bixby Hill Rd",
  },
  {
    ID: 14,
    FirstName: "Walter",
    LastName: "Hobbs",
    Gender: "Male",
    "Date of Birth": "1984/12/24",
    Address: "10385 Shadow Oak Dr",
  },
  {
    ID: 15,
    FirstName: "Mary",
    LastName: "Heart",
    Gender: "Male",
    "Date of Birth": "1964/03/16",
    Address: "351 S Hill St.",
  },
  {
    ID: 16,
    FirstName: "Suellen",
    LastName: "Peyton",
    Gender: "Male",
    "Date of Birth": "1981/06/03",
    Address: "807 W Paseo Del Mar",
  },
  {
    ID: 17,
    FirstName: "Barmen",
    LastName: "Reagan",
    Gender: "Male",
    "Date of Birth": "1974/09/07",
    Address: "4 Westmoreland Pl.",
  },
  {
    ID: 18,
    FirstName: "Kriskoff",
    LastName: "Sims",
    Gender: "Male",
    "Date of Birth": "1977/11/22",
    Address: "1700 S Grandview Dr.",
  },
  {
    ID: 19,
    FirstName: "Adam",
    LastName: "Wade",
    Gender: "Male",
    "Date of Birth": "1968/12/01",
    Address: "1120 Old Mill Rd.",
  },
  {
    ID: 20,
    FirstName: "Lossary",
    LastName: "Johnson",
    Gender: "Male",
    "Date of Birth": "1974/11/15",
    Address: "4600 N Virginia Rd.",
  },
  {
    ID: 21,
    FirstName: "Peter",
    LastName: "Carter",
    Gender: "Male",
    "Date of Birth": "1978/01/09",
    Address: "424 N Main St.",
  },
  {
    ID: 22,
    FirstName: "Sthefany",
    LastName: "Stanwick",
    Gender: "Male",
    "Date of Birth": "1985/06/05",
    Address: "2211 Bonita Dr.",
  },
  {
    ID: 23,
    FirstName: "Thalita",
    LastName: "Samuelson",
    Gender: "Male",
    "Date of Birth": "1972/09/11",
    Address: "12100 Mora Dr",
  },
  {
    ID: 24,
    FirstName: "Swift",
    LastName: "Riley",
    Gender: "Male",
    "Date of Birth": "1982/08/14",
    Address: "7776 Torreyson Dr",
  },
  {
    ID: 25,
    FirstName: "Sam",
    LastName: "Hill",
    Gender: "Male",
    "Date of Birth": "1984/02/17",
    Address: "645 Prospect Crescent",
  },
  {
    ID: 26,
    FirstName: "Kelly",
    LastName: "Rodriguez",
    Gender: "Male",
    "Date of Birth": "1988/05/11",
    Address: "1601 W Mountain St.",
  },
  {
    ID: 27,
    FirstName: "Natalie",
    LastName: "Maguirre",
    Gender: "Male",
    "Date of Birth": "1977/10/07",
    Address: "6400 E Bixby Hill Rd",
  },
  {
    ID: 28,
    FirstName: "Walter",
    LastName: "Hobbs",
    Gender: "Male",
    "Date of Birth": "1984/12/24",
    Address: "10385 Shadow Oak Dr",
  },
];
